### ISSUE TITLE
Steph's dev environment -- issues

### ISSUE THREAD

**Issue by nguyenist-zz** [ProjectSidewalk/Instructions#1]
1. Ran `Stephanies-MacBook-Pro:Sidewalk-instructions-master Stephanie$ vagrant up`

Loading seemed to finish and then: 

`The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`
1. Then ran `vagrant ssh`

```
Stephanies-MacBook-Pro:Sidewalk-instructions-master Stephanie$ vagrant ssh
Welcome to Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-85-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

 System information disabled due to load higher than 1.0

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.
```
1. Then ran: 

```
vagrant@vagrant-ubuntu-trusty-64:~$ psql -d sidewalk
psql (9.5.2, server 9.3.12)
Type "help" for help.

sidewalk=> help
You are using psql, the command-line interface to PostgreSQL.
Type:  \copyright for distribution terms
       \h for help with SQL commands
       \? for help with psql commands
       \g or terminate with semicolon to execute query
       \q to quit
sidewalk=> \du
                             List of roles
 Role name |                   Attributes                   | Member of 
-----------+------------------------------------------------+-----------
 postgres  | Superuser, Create role, Create DB, Replication | {}
 vagrant   |                                                | {}

sidewalk=> sudo su - postgres
sidewalk-> help
sidewalk-> sudo su - postgres
sidewalk-> 
```

**Comment by nguyenist-zz** [comment]
Also
![image](https://cloud.githubusercontent.com/assets/4484141/14406000/40bfed1c-fe6a-11e5-9cfd-e6b9c2304cd4.png)

![image](https://cloud.githubusercontent.com/assets/4484141/14405999/396179dc-fe6a-11e5-83ab-3bfb5efaa043.png)

**Comment by nguyenist-zz** [comment]
@kotarohara perhaps the problem was in step 1 from above? Not sure if `vagrant up` 100% worked for me. Let me know if you see something different / might know where I went wrong.

**Comment by kotarohara** [comment]
@nguyenist Try running `psql -d sidewalk -a -f sidewalk.sql` first? It would create a user `sidewalk`.

**Comment by nguyenist-zz** [comment]
`Stephanies-MacBook-Pro:Sidewalk-instructions-master Stephanie$ psql -d sidewalk -a -f sidewalk.sql
-bash: psql: command not found`

**Comment by nguyenist-zz** [comment]
To restart the website host

Route to:

```
cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/
```

```
cd public/javascripts/SVLabel/
grunt watch
```

In another tab

```
cd public/javascripts/SVLabel/
sbt run
```

To close out
`control + c`

**Comment by nguyenist-zz** [comment]
@kotarohara do you know if I'm missing something here? followed instruction above like last time. 

```
Stephanies-MacBook-Pro:SVLabel Stephanie$ sbt run
[info] Set current project to svlabel (in build file:/Users/Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/public/javascripts/SVLabel/)
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 2 s, completed Apr 12, 2016 8:18:29 PM
```

![image](https://cloud.githubusercontent.com/assets/4484141/14479407/1a44b90e-00ec-11e6-8556-c32f72223f48.png)

**Comment by nguyenist-zz** [comment]
Specifically: 

In one tab, route to: `cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/`
Then

```
cd public/javascripts/SVLabel/
grunt watch
```

Then in a different tab in `cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/` (where build.sbt is located)

```
sbt run
```

**Comment by nguyenist-zz** [comment]
Nevermind got it!!! Wrong directory before.

**Comment by nguyenist-zz** [comment]
@kotarohara 

(1) When I route to: `cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/`
Then

```
cd public/javascripts/SVLabel/
grunt watch
```

My terminal gets stuck at `Waiting...`

(2) When I go to `cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/` (where built.sbt is located) I get: `-bash: sbt: command not found`

**Comment by nguyenist-zz** [comment]
New instructions:
`cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/`
`sbt run`

`cd ~Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/`
`grunt watch`

have these two tabs running in parallel in terminal

**Comment by nguyenist-zz** [comment]
Also keep postico up and running.

**Comment by nguyenist-zz** [comment]
@kotarohara -- getting more errors that stop me from launching the localhost:9000/. Any idea why this is popping up? I just merged directory from master so the files should be the same. 

```
Stephanies-MacBook-Pro:sidewalk-webpage Stephanie$ grunt watch
>> Local Npm module "grunt-contrib-concat" not found. Is it installed?
>> Local Npm module "grunt-concat-css" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-jsdoc" not found. Is it installed?
>> Local Npm module "grunt-contrib-watch" not found. Is it installed?
>> Local Npm module "grunt-contrib-jasmine" not found. Is it installed?
Warning: Task "watch" not found. Use --force to continue.
```

**Comment by nguyenist-zz** [comment]
This is the error for `sbt run`

```
Stephanies-MacBook-Pro:sidewalk-webpage Stephanie$ sbt run
Getting org.scala-sbt sbt 0.13.11 ...
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/0.13.11/jars/sbt.jar ...
    [SUCCESSFUL ] org.scala-sbt#sbt;0.13.11!sbt.jar (1642ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.10.6/scala-library-2.10.6.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-library;2.10.6!scala-library.jar (5995ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main/0.13.11/jars/main.jar ...
    [SUCCESSFUL ] org.scala-sbt#main;0.13.11!main.jar (4906ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-interface/0.13.11/jars/compiler-interface.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-interface;0.13.11!compiler-interface.jar (2419ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/actions/0.13.11/jars/actions.jar ...
    [SUCCESSFUL ] org.scala-sbt#actions;0.13.11!actions.jar (1816ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/main-settings/0.13.11/jars/main-settings.jar ...
    [SUCCESSFUL ] org.scala-sbt#main-settings;0.13.11!main-settings.jar (1985ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/interface/0.13.11/jars/interface.jar ...
    [SUCCESSFUL ] org.scala-sbt#interface;0.13.11!interface.jar (2099ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/io/0.13.11/jars/io.jar ...
    [SUCCESSFUL ] org.scala-sbt#io;0.13.11!io.jar (1886ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/ivy/0.13.11/jars/ivy.jar ...
    [SUCCESSFUL ] org.scala-sbt#ivy;0.13.11!ivy.jar (3026ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logging/0.13.11/jars/logging.jar ...
    [SUCCESSFUL ] org.scala-sbt#logging;0.13.11!logging.jar (1874ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/logic/0.13.11/jars/logic.jar ...
    [SUCCESSFUL ] org.scala-sbt#logic;0.13.11!logic.jar (1661ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/process/0.13.11/jars/process.jar ...
    [SUCCESSFUL ] org.scala-sbt#process;0.13.11!process.jar (1753ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/run/0.13.11/jars/run.jar ...
    [SUCCESSFUL ] org.scala-sbt#run;0.13.11!run.jar (1730ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/command/0.13.11/jars/command.jar ...
    [SUCCESSFUL ] org.scala-sbt#command;0.13.11!command.jar (2086ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/launcher-interface/1.0.0-M1/launcher-interface-1.0.0-M1.jar ...
    [SUCCESSFUL ] org.scala-sbt#launcher-interface;1.0.0-M1!launcher-interface.jar (902ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classpath/0.13.11/jars/classpath.jar ...
    [SUCCESSFUL ] org.scala-sbt#classpath;0.13.11!classpath.jar (1782ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/completion/0.13.11/jars/completion.jar ...
    [SUCCESSFUL ] org.scala-sbt#completion;0.13.11!completion.jar (2112ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/api/0.13.11/jars/api.jar ...
    [SUCCESSFUL ] org.scala-sbt#api;0.13.11!api.jar (1922ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-integration/0.13.11/jars/compiler-integration.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-integration;0.13.11!compiler-integration.jar (2340ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compiler-ivy-integration/0.13.11/jars/compiler-ivy-integration.jar ...
    [SUCCESSFUL ] org.scala-sbt#compiler-ivy-integration;0.13.11!compiler-ivy-integration.jar (1676ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/relation/0.13.11/jars/relation.jar ...
    [SUCCESSFUL ] org.scala-sbt#relation;0.13.11!relation.jar (1599ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/task-system/0.13.11/jars/task-system.jar ...
    [SUCCESSFUL ] org.scala-sbt#task-system;0.13.11!task-system.jar (1738ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tasks/0.13.11/jars/tasks.jar ...
    [SUCCESSFUL ] org.scala-sbt#tasks;0.13.11!tasks.jar (1640ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/tracking/0.13.11/jars/tracking.jar ...
    [SUCCESSFUL ] org.scala-sbt#tracking;0.13.11!tracking.jar (1598ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/testing/0.13.11/jars/testing.jar ...
    [SUCCESSFUL ] org.scala-sbt#testing;0.13.11!testing.jar (1676ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.10.6/scala-compiler-2.10.6.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-compiler;2.10.6!scala-compiler.jar (16511ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.10.6/scala-reflect-2.10.6.jar ...
    [SUCCESSFUL ] org.scala-lang#scala-reflect;2.10.6!scala-reflect.jar (5855ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/control/0.13.11/jars/control.jar ...
    [SUCCESSFUL ] org.scala-sbt#control;0.13.11!control.jar (1992ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/collections/0.13.11/jars/collections.jar ...
    [SUCCESSFUL ] org.scala-sbt#collections;0.13.11!collections.jar (3505ms)
downloading https://repo1.maven.org/maven2/jline/jline/2.13/jline-2.13.jar ...
    [SUCCESSFUL ] jline#jline;2.13!jline.jar (979ms)
downloading https://repo1.maven.org/maven2/org/fusesource/jansi/jansi/1.11/jansi-1.11.jar ...
    [SUCCESSFUL ] org.fusesource.jansi#jansi;1.11!jansi.jar (405ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/classfile/0.13.11/jars/classfile.jar ...
    [SUCCESSFUL ] org.scala-sbt#classfile;0.13.11!classfile.jar (2000ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/incremental-compiler/0.13.11/jars/incremental-compiler.jar ...
    [SUCCESSFUL ] org.scala-sbt#incremental-compiler;0.13.11!incremental-compiler.jar (2483ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/compile/0.13.11/jars/compile.jar ...
    [SUCCESSFUL ] org.scala-sbt#compile;0.13.11!compile.jar (1822ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/persist/0.13.11/jars/persist.jar ...
    [SUCCESSFUL ] org.scala-sbt#persist;0.13.11!persist.jar (1921ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cross/0.13.11/jars/cross.jar ...
    [SUCCESSFUL ] org.scala-sbt#cross;0.13.11!cross.jar (1445ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/ivy/ivy/2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a/ivy-2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a.jar ...
    [SUCCESSFUL ] org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435c4fa24f9a!ivy.jar (1727ms)
downloading https://repo1.maven.org/maven2/org/scala-sbt/serialization_2.10/0.1.2/serialization_2.10-0.1.2.jar ...
    [SUCCESSFUL ] org.scala-sbt#serialization_2.10;0.1.2!serialization_2.10.jar (537ms)
downloading https://repo1.maven.org/maven2/org/scala-lang/modules/scala-pickling_2.10/0.10.1/scala-pickling_2.10-0.10.1.jar ...
    [SUCCESSFUL ] org.scala-lang.modules#scala-pickling_2.10;0.10.1!scala-pickling_2.10.jar (702ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-core_2.10/3.2.10/json4s-core_2.10-3.2.10.jar ...
    [SUCCESSFUL ] org.json4s#json4s-core_2.10;3.2.10!json4s-core_2.10.jar (570ms)
downloading https://repo1.maven.org/maven2/org/spire-math/jawn-parser_2.10/0.6.0/jawn-parser_2.10-0.6.0.jar ...
    [SUCCESSFUL ] org.spire-math#jawn-parser_2.10;0.6.0!jawn-parser_2.10.jar (284ms)
downloading https://repo1.maven.org/maven2/org/spire-math/json4s-support_2.10/0.6.0/json4s-support_2.10-0.6.0.jar ...
    [SUCCESSFUL ] org.spire-math#json4s-support_2.10;0.6.0!json4s-support_2.10.jar (263ms)
downloading https://repo1.maven.org/maven2/org/scalamacros/quasiquotes_2.10/2.0.1/quasiquotes_2.10-2.0.1.jar ...
    [SUCCESSFUL ] org.scalamacros#quasiquotes_2.10;2.0.1!quasiquotes_2.10.jar (650ms)
downloading https://repo1.maven.org/maven2/org/json4s/json4s-ast_2.10/3.2.10/json4s-ast_2.10-3.2.10.jar ...
    [SUCCESSFUL ] org.json4s#json4s-ast_2.10;3.2.10!json4s-ast_2.10.jar (331ms)
downloading https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.6/paranamer-2.6.jar ...
    [SUCCESSFUL ] com.thoughtworks.paranamer#paranamer;2.6!paranamer.jar (290ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/cache/0.13.11/jars/cache.jar ...
    [SUCCESSFUL ] org.scala-sbt#cache;0.13.11!cache.jar (1906ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/test-agent/0.13.11/jars/test-agent.jar ...
    [SUCCESSFUL ] org.scala-sbt#test-agent;0.13.11!test-agent.jar (1478ms)
downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/apply-macro/0.13.11/jars/apply-macro.jar ...
    [SUCCESSFUL ] org.scala-sbt#apply-macro;0.13.11!apply-macro.jar (1742ms)
:: retrieving :: org.scala-sbt#boot-app
    confs: [default]
    49 artifacts copied, 0 already retrieved (17330kB/1464ms)
Getting Scala 2.10.6 (for sbt)...
downloading https://repo1.maven.org/maven2/org/scala-lang/jline/2.10.6/jline-2.10.6.jar ...
    [SUCCESSFUL ] org.scala-lang#jline;2.10.6!jline.jar (449ms)
:: retrieving :: org.scala-sbt#boot-scala
    confs: [default]
    5 artifacts copied, 0 already retrieved (24494kB/570ms)
[info] Loading project definition from /Users/Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/project
[info] Updating {file:/Users/Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/project/}sidewalk-webpage-build...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-2cc8d2761242b072cedb0a04cb39435[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to sidewalk-webpage (in build file:/Users/Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/)
[info] Updating {file:/Users/Stephanie/Documents/Development/SidewalkWebpage/sidewalk-webpage/}sidewalk-webpage...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
java.lang.RuntimeException: No main class detected.
    at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) No main class detected.
[error] Total time: 1 s, completed May 30, 2016 9:49:48 PM
```

**Comment by nguyenist-zz** [comment]
@kotarohara I uploaded the new sidewalk dataset successfully: https://www.dropbox.com/s/y9ghi2dnues3txr/2016-07-07_SidewalkSQLDump.anonymized.sql?dl=0

Tonight I have been working setup again. Am getting this error when trying to launch the website locally. Any idea what this might be? I followed all steps in: https://github.com/ProjectSidewalk/SidewalkWebpage
![image](https://cloud.githubusercontent.com/assets/4484141/16711510/a4228148-462d-11e6-94b1-4c41488874b4.png)

**Comment by kotarohara** [comment]
That means you don't have a table called sidewalk.webpage_activity in your
database :( you should look at the database using db client like postico
and see why it's happening. My guess is you did not import the latest SQL
file.

**Comment by nguyenist-zz** [comment]
Thanks for letting me know! I will try again.

**Comment by nguyenist-zz** [comment]
hey @kotarohara. i tried restarting the steps several times. The `onError Happened` is still there, but I'm seeing a new error (below) on step 3 of this: 
![image](https://cloud.githubusercontent.com/assets/4484141/16715926/21913a8c-46bc-11e6-9d0c-7f51e7cab5d0.png)

Do you have any advice on this portion? I tried changing the port on the Postico login to "1234" but that did not connect.

```
To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 5432, host: 1234
```

```
Stephanies-MacBook-Pro:Instructions Stephanie$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20160323.1.0'. The latest is version '20160707.0.1'. Run
==> default: `vagrant box update` to update.
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 5432 is already in use
on the host machine.

To fix this, modify your current project's Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 5432, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

**Comment by nguyenist-zz** [comment]
Also, where is the `vagrant > resources` path as mentioned below in:
![image](https://cloud.githubusercontent.com/assets/4484141/16715946/975ce7e8-46bc-11e6-9c36-c5c2245ee8b7.png)

In my `SidewalkWebpage` directory I see these files: 
![image](https://cloud.githubusercontent.com/assets/4484141/16715949/ad967646-46bc-11e6-9d37-c9c44ad28cbf.png)

In my `Instructions` directory I see these files: 
![image](https://cloud.githubusercontent.com/assets/4484141/16715950/ba4f04b6-46bc-11e6-9a26-3c905b17272e.png)

Both do not have a `vagrant > resources` file, unless you would like me to create one, then place the new Sidewalk.sql file inside, let me know what is best. (https://www.dropbox.com/s/y9ghi2dnues3txr/2016-07-07_SidewalkSQLDump.anonymized.sql?dl=0)

**Comment by kotarohara** [comment]
Not sure about the error, but you may be running multiple instances of virtual machines and the one you started running previously is occupying port 5432. I recommend opening Virtual Box and see if any instance is running already.

You should make resources file under `Instruction` folder.
